In [2]:
import pandas as pd
import numpy
import json

In [56]:
homeless = pd.read_csv("../data/external/homeless.csv")

In [57]:
homeless.tail()

,CoC Number,CoC Name,Year,Attribute Name,Value,Year - Text
25510,WY-500,Wyoming Statewide CoC,01/01/2015 12:00:00 AM,Homeless People in Families,298,2015
25511,WY-500,Wyoming Statewide CoC,01/01/2015 12:00:00 AM,Sheltered Homeless Veterans,83,2015
25512,WY-500,Wyoming Statewide CoC,01/01/2015 12:00:00 AM,Parenting Youth Age 18-24,12,2015
25513,WY-500,Wyoming Statewide CoC,01/01/2015 12:00:00 AM,Parenting Youth (Under 25),12,2015
25514,WY-500,Wyoming Statewide CoC,01/01/2015 12:00:00 AM,Unsheltered Parenting Youth Under 18,0,2015

In [58]:
homeless["Year - Text"].unique()

array([2014, 2015])

In [59]:
for i in homeless.index.values.tolist():
    homeless.at[i, "State"] = str(homeless.at[i, "CoC Number"])[:2]

In [60]:
homeless[homeless["CoC Name"]=="Anchorage CoC"]

,CoC Number,CoC Name,Year,Attribute Name,Value,Year - Text,State
0,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Chronically Homeless,101,2014,AK
1,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Sheltered Homeless People in Families,282,2014,AK
2,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Homeless Individuals,736,2014,AK
3,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Homeless People in Families,287,2014,AK
4,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Unsheltered Homeless Individuals,48,2014,AK
5,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Unsheltered Homeless Veterans,18,2014,AK
6,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Sheltered Homeless,970,2014,AK
7,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Total Homeless,1023,2014,AK
8,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Chronically Homeless People in Families,7,2014,AK
9,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Unsheltered Homeless,53,2014,AK
10,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Homeless Veterans,138,2014,AK
11,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Unsheltered Chronically Homeless People in Fam...,4,2014,AK
12,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Unsheltered Chronically Homeless,42,2014,AK
13,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Unsheltered Chronically Homeless Individuals,38,2014,AK
14,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Sheltered Chronically Homeless People in Families,3,2014,AK
15,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Sheltered Chronically Homeless,59,2014,AK
16,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Sheltered Chronically Homeless Individuals,56,2014,AK
17,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Unsheltered Homeless People in Families,5,2014,AK
18,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Sheltered Homeless Veterans,120,2014,AK
19,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Chronically Homeless Individuals,94,2014,AK
20,AK-500,Anchorage CoC,01/01/2014 12:00:00 AM,Sheltered Homeless Individuals,688,2014,AK
8468,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Homeless,179,2015,AK
8469,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Parenting Youth Under 18,0,2015,AK
8470,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Chronically Homeless,127,2015,AK
8471,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Parenting Youth (Under 25),15,2015,AK
8472,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Chronically Homeless Individuals,27,2015,AK
8473,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Homeless Unaccompanied Youth (Unde...,23,2015,AK
8474,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Homeless Veterans,22,2015,AK
8475,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Homeless Unaccompanied Children (Under 18),12,2015,AK
8476,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Homeless Unaccompanied Youth (Under 25),106,2015,AK
...,...,...,...,...,...,...,...
8480,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Total Homeless,1208,2015,AK
8481,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Homeless Individuals,158,2015,AK
8482,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Homeless Unaccompanied Children (Und...,9,2015,AK
8483,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Homeless Veterans,130,2015,AK
8484,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Chronically Homeless Individuals,106,2015,AK
8485,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Homeless Unaccompanied Youth (Under 25),83,2015,AK
8486,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Homeless Unaccompanied Young Adults ...,74,2015,AK
8487,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Chronically Homeless People in Families,21,2015,AK
8488,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Children of Parenting Youth,0,2015,AK
8489,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Homeless Individuals,679,2015,AK
8490,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Homeless People in Families,350,2015,AK
8491,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Homeless Unaccompanied Young Adult...,20,2015,AK
8492,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Chronically Homeless,100,2015,AK
8493,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Parenting Youth Age 18-24,0,2015,AK
8494,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Homeless Individuals,837,2015,AK
8495,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Homeless,1029,2015,AK
8496,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Chronically Homeless Individuals,79,2015,AK
8497,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Homeless People in Families,21,2015,AK
8498,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Chronically Homeless People in Fam...,21,2015,AK
8499,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Homeless Unaccompanied Children (U...,3,2015,AK
8500,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Parenting Youth (Under 25),0,2015,AK
8501,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Parenting Youth Age 18-24,15,2015,AK
8502,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Children of Parenting Youth,16,2015,AK
8503,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Chronically Homeless People in Families,0,2015,AK
8504,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Children of Parenting Youth,16,2015,AK
8505,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Homeless People in Families,371,2015,AK
8506,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Sheltered Homeless Veterans,108,2015,AK
8507,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Parenting Youth Age 18-24,15,2015,AK
8508,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Parenting Youth (Under 25),15,2015,AK
8509,AK-500,Anchorage CoC,01/01/2015 12:00:00 AM,Unsheltered Parenting Youth Under 18,0,2015,AK

In [61]:
len(homeless["CoC Name"].unique())

407

In [62]:
homless = homeless[homeless["Attribute Name"]=="Total Homeless"]

In [63]:
homeless.drop(columns=["CoC Name"], inplace=True)

In [65]:
homeless.drop(columns=["CoC Number"], inplace=True)

In [66]:
homeless[homeless["Attribute Name"]=="Total Homeless"]

                         Year  Attribute Name  Value  Year - Text State
7      01/01/2014 12:00:00 AM  Total Homeless   1023         2014    AK
28     01/01/2014 12:00:00 AM  Total Homeless    761         2014    AK
49     01/01/2014 12:00:00 AM  Total Homeless   1329         2014    AL
70     01/01/2014 12:00:00 AM  Total Homeless    598         2014    AL
91     01/01/2014 12:00:00 AM  Total Homeless    209         2014    AL
113    01/01/2014 12:00:00 AM  Total Homeless    536         2014    AL
134    01/01/2014 12:00:00 AM  Total Homeless    490         2014    AL
155    01/01/2014 12:00:00 AM  Total Homeless    438         2014    AL
176    01/01/2014 12:00:00 AM  Total Homeless    245         2014    AL
197    01/01/2014 12:00:00 AM  Total Homeless    716         2014    AL
219    01/01/2014 12:00:00 AM  Total Homeless   1074         2014    AR
240    01/01/2014 12:00:00 AM  Total Homeless    551         2014    AR
261    01/01/2014 12:00:00 AM  Total Homeless   1028         2014    AR
282    01/01/2014 12:00:00 AM  Total Homeless     70         2014    AR
303    01/01/2014 12:00:00 AM  Total Homeless    185         2014    AR
324    01/01/2014 12:00:00 AM  Total Homeless     28         2014    AR
345    01/01/2014 12:00:00 AM  Total Homeless   2398         2014    AZ
366    01/01/2014 12:00:00 AM  Total Homeless   2179         2014    AZ
387    01/01/2014 12:00:00 AM  Total Homeless   5918         2014    AZ
408    01/01/2014 12:00:00 AM  Total Homeless   7567         2014    CA
429    01/01/2014 12:00:00 AM  Total Homeless   6408         2014    CA
450    01/01/2014 12:00:00 AM  Total Homeless   4272         2014    CA
471    01/01/2014 12:00:00 AM  Total Homeless   2449         2014    CA
493    01/01/2014 12:00:00 AM  Total Homeless   4266         2014    CA
514    01/01/2014 12:00:00 AM  Total Homeless   2009         2014    CA
535    01/01/2014 12:00:00 AM  Total Homeless   2962         2014    CA
555    01/01/2014 12:00:00 AM  Total Homeless    679         2014    CA
576    01/01/2014 12:00:00 AM  Total Homeless   3529         2014    CA
597    01/01/2014 12:00:00 AM  Total Homeless   1404         2014    CA
618    01/01/2014 12:00:00 AM  Total Homeless   1156         2014    CA
...                       ...             ...    ...          ...   ...
24226  01/01/2015 12:00:00 AM  Total Homeless    185         2015    VA
24268  01/01/2015 12:00:00 AM  Total Homeless    520         2015    VA
24351  01/01/2015 12:00:00 AM  Total Homeless    237         2015    VA
24394  01/01/2015 12:00:00 AM  Total Homeless    242         2015    VA
24436  01/01/2015 12:00:00 AM  Total Homeless    217         2015    VA
24478  01/01/2015 12:00:00 AM  Total Homeless    773         2015    VA
24520  01/01/2015 12:00:00 AM  Total Homeless    239         2015    VA
24562  01/01/2015 12:00:00 AM  Total Homeless   1204         2015    VA
24603  01/01/2015 12:00:00 AM  Total Homeless    172         2015    VA
24645  01/01/2015 12:00:00 AM  Total Homeless    267         2015    VA
24687  01/01/2015 12:00:00 AM  Total Homeless    409         2015    VA
24729  01/01/2015 12:00:00 AM  Total Homeless    337         2015    VI
24771  01/01/2015 12:00:00 AM  Total Homeless   1052         2015    VT
24813  01/01/2015 12:00:00 AM  Total Homeless    471         2015    VT
24855  01/01/2015 12:00:00 AM  Total Homeless  10122         2015    WA
24897  01/01/2015 12:00:00 AM  Total Homeless   4951         2015    WA
24939  01/01/2015 12:00:00 AM  Total Homeless   1034         2015    WA
24981  01/01/2015 12:00:00 AM  Total Homeless   1283         2015    WA
25023  01/01/2015 12:00:00 AM  Total Homeless    829         2015    WA
25065  01/01/2015 12:00:00 AM  Total Homeless    538         2015    WA
25107  01/01/2015 12:00:00 AM  Total Homeless    662         2015    WA
25149  01/01/2015 12:00:00 AM  Total Homeless   3597         2015    WI
25191  01/01/2015 12:00:00 AM  Total Homeless   1521         2015    WI
25233  01/01/2015 12:00:00 AM  Total Homeless    168         2015    WI
25275  01/01/2015 12:00:00 AM  Total Homeless    771         2015    WI
25317  01/01/2015 12:00:00 AM  Total Homeless    114         2015    WV
25359  01/01/2015 12:00:00 AM  Total Homeless    227         2015    WV
25401  01/01/2015 12:00:00 AM  Total Homeless    385         2015    WV
25443  01/01/2015 12:00:00 AM  Total Homeless   1109         2015    WV
25485  01/01/2015 12:00:00 AM  Total Homeless    798         2015    WY

[809 rows x 5 columns]